update on xmltest.sh's and code_coverage.sh.in's

diff --git a/scai/blaskernel/test/code_coverage.sh.in b/scai/blaskernel/test/code_coverage.sh.in
--- a/scai/blaskernel/test/code_coverage.sh.in
+++ b/scai/blaskernel/test/code_coverage.sh.in
@@ -52,14 +52,26 @@ cd ..
 export SCAI_LOG=TRACE
 export SCAI_TRACE=time
 	
-# Running tests serial
+# Running blaskernel serial
 echo "Running serial tests"
-./BLASKernelTest >/dev/null
+./blaskernelTest >/dev/null
 if [ $? -ne 0 ]
 then
-	echo "ERROR in BLASKernelTest"
+	echo "ERROR in blaskernelTest"
 	error_count=$(($error_count + $?))
 fi
+
+#if [ -d ../cuda ];
+#then
+    #Running common CUDA tests
+    echo "Running blaskernel tests with CUDA context"
+    ./blaskernelTest --SCAI_CONTEXT=CUDA >/dev/null
+    if [ $? -ne 0 ]
+    then
+        echo "ERROR in blaskernelTest with CUDA context"
+        error_count=$(($error_count + $?))
+    fi
+#fi
 
 cd ${dirname}
 
diff --git a/scai/lama/test/code_coverage.sh.in b/scai/lama/test/code_coverage.sh.in
--- a/scai/lama/test/code_coverage.sh.in
+++ b/scai/lama/test/code_coverage.sh.in
@@ -52,21 +52,38 @@ cd ..
 export SCAI_LOG=TRACE
 export SCAI_TRACE=time
 	
-# Running tests serial
-echo "Running serial tests"
-./lama_test >/dev/null
+# Running lama tests
+echo "Running serial lama tests"
+./lamaTest >/dev/null
 if [ $? -ne 0 ]
 then
 	echo "ERROR in lama_test"
 	error_count=$(($error_count + $?))
 fi
 
+#Running lama storage tests
+echo "Running serial lama storage tests"
+./storage/lamaStorageTest >/dev/null
+if [ $? -ne 0 ]
+then
+    echo "ERROR in lamaStorageTest"
+    error_count=$(($error_count + $?))
+fi
+
+#Running lama matrix tests
+echo "Running serial lama matrix tests"
+./matrix/lamaMatrixTest >/dev/null
+if [ $? -ne 0 ]
+then
+    echo "ERROR in lamaMatrixTest"
+    error_count=$(($error_count + $?))
+fi
+
 if [ -d distributed ];
 then
     # Running parallel tests serial and with two processes
-    cd distributed
     echo "Running distributed tests serial"
-    ./lama_dist_test >/dev/null
+    ./distributed/lamaDistTest >/dev/null
     if [ $? -ne 0 ]
     then
         echo "ERROR in lama_dist_test"
@@ -76,29 +93,44 @@ then
     for i in 2 3 4;
     do
         echo "Running distributed tests with $i processes"
-        mpirun -np $i ./lama_dist_test >/dev/null
+        mpirun -np $i ./distributed/lamaDistTest >/dev/null
         if [ $? -ne 0 ]
         then
-            echo "ERROR in lama_dist_test"
+            echo "ERROR in lamaDistTest with $i processes"
             error_count=$(($error_count + $?))
         fi
     done
-    cd ..
 fi
     
     
 if [ -d cuda ];
 then
-	#Running CUDA tests
-	cd cuda
-	echo "Running cuda tests"
-	./lama_cuda_test >/dev/null
-	if [ $? -ne 0 ]
-	then
-		echo "ERROR in lama_cuda_test"
-		error_count=$(($error_count + $?))
-	fi
-	cd ..
+    # Running lama tests
+    echo "Running serial lama tests"
+    ./lamaTest --SCAI_CONTEXT=CUDA >/dev/null
+    if [ $? -ne 0 ]
+    then
+        echo "ERROR in lama_test"
+        error_count=$(($error_count + $?))
+    fi
+
+    #Running lama storage tests
+    echo "Running serial lama storage tests"
+    ./storage/lamaStorageTest --SCAI_CONTEXT=CUDA >/dev/null
+    if [ $? -ne 0 ]
+    then
+        echo "ERROR in lamaStorageTest"
+        error_count=$(($error_count + $?))
+    fi
+
+    #Running lama matrix tests
+    echo "Running serial lama matrix tests"
+    ./matrix/lamaMatrixTest --SCAI_CONTEXT=CUDA >/dev/null
+    if [ $? -ne 0 ]
+    then
+        echo "ERROR in lamaMatrixTest"
+        error_count=$(($error_count + $?))
+    fi
 fi
 
 cd ${dirname}
@@ -132,4 +164,4 @@ then
     exit 1
 fi
 
-zip -r ../coverage.zip *
+zip -r ../lama_coverage.zip *
diff --git a/scai/solver/test/code_coverage.sh.in b/scai/solver/test/code_coverage.sh.in
--- a/scai/solver/test/code_coverage.sh.in
+++ b/scai/solver/test/code_coverage.sh.in
@@ -54,14 +54,23 @@ export SCAI_TRACE=time
 	
 # Running tests serial
 echo "Running serial tests"
-./SolverTest >/dev/null
+./solverTest >/dev/null
 if [ $? -ne 0 ]
 then
-	echo "ERROR in SolverTest"
+	echo "ERROR in solverTest"
 	error_count=$(($error_count + $?))
 fi
     
-    
+if [ -d distributed ];
+then    
+	echo "Running distributed tests"
+	./distributed/solverDistTest >/dev/null
+	if [ $? -ne 0 ]
+	then
+		echo "ERROR in solverDistTest"
+		error_count=$(($error_count + $?))
+	fi
+fi
 
 cd ${dirname}
 
diff --git a/scai/sparsekernel/test/code_coverage.sh.in b/scai/sparsekernel/test/code_coverage.sh.in
--- a/scai/sparsekernel/test/code_coverage.sh.in
+++ b/scai/sparsekernel/test/code_coverage.sh.in
@@ -54,11 +54,23 @@ export SCAI_TRACE=time
 	
 # Running tests serial
 echo "Running serial tests"
-./SparseKernelTest >/dev/null
+./sparsekernelTest >/dev/null
 if [ $? -ne 0 ]
 then
-	echo "ERROR in SparseKernelTest"
+	echo "ERROR in sparsekernelTest"
 	error_count=$(($error_count + $?))
+fi
+
+if [ -d ../cuda ];
+then
+    #Running common CUDA tests
+    echo "Running blaskernel tests with CUDA context"
+    ./sparsekernelTest --SCAI_CONTEXT=CUDA >/dev/null
+    if [ $? -ne 0 ]
+    then
+        echo "ERROR in sparsekernelTest with CUDA context"
+        error_count=$(($error_count + $?))
+    fi
 fi
 
 cd ${dirname}
diff --git a/scai/tasking/test/code_coverage.sh.in b/scai/tasking/test/code_coverage.sh.in
--- a/scai/tasking/test/code_coverage.sh.in
+++ b/scai/tasking/test/code_coverage.sh.in
@@ -54,11 +54,23 @@ export SCAI_TRACE=time
 	
 # Running tests serial
 echo "Running serial tests"
-./CommonTest >/dev/null
+./taskingTest >/dev/null
 if [ $? -ne 0 ]
 then
-	echo "ERROR in CommonTest"
+	echo "ERROR in taskingTest"
 	error_count=$(($error_count + $?))
+fi
+
+if [ -d cuda ];
+then
+    #Running common CUDA tests
+    echo "Running common CUDA tests"
+    ./cuda/taskingCUDATest >/dev/null
+    if [ $? -ne 0 ]
+    then
+        echo "ERROR in taskingCUDATest"
+        error_count=$(($error_count + $?))
+    fi
 fi
 
 cd ${dirname}
@@ -92,4 +104,4 @@ then
     exit 1
 fi
 
-zip -r ../coverage.zip *
+zip -r ../tasking_coverage.zip *
diff --git a/scai/utilskernel/test/code_coverage.sh.in b/scai/utilskernel/test/code_coverage.sh.in
--- a/scai/utilskernel/test/code_coverage.sh.in
+++ b/scai/utilskernel/test/code_coverage.sh.in
@@ -54,11 +54,23 @@ export SCAI_TRACE=time
 	
 # Running tests serial
 echo "Running serial tests"
-./UtilsKernelTest >/dev/null
+./utilskernelTest >/dev/null
 if [ $? -ne 0 ]
 then
-	echo "ERROR in UtilsKernelTest"
+	echo "ERROR in utilskernelTest"
 	error_count=$(($error_count + $?))
+fi
+
+if [ -d ../cuda ];
+then
+    #Running common CUDA tests
+    echo "Running blaskernel tests with CUDA context"
+    ./utilskernelTest --SCAI_CONTEXT=CUDA >/dev/null
+    if [ $? -ne 0 ]
+    then
+        echo "ERROR in utilskernelTest with CUDA context"
+        error_count=$(($error_count + $?))
+    fi
 fi
 
 cd ${dirname}
